spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost/notes?characterEncoding=utf-8
    username: notes
    password: notes
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
server:
  context-path: /notes